version: "3"

services:
  node:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd web && npm install && npm run dev"
    ports:
      - "80:3000"
    container_name: node-container

  golang:
    image: golang:1.18.2
    ports:
      - 8080:8080
#    command: sh -c "cd /go/src && go mod init gidai-pastprob && go run ./api/cmd/main.go"
    command: sh -c "cd /go/src/api && go run ./cmd/main.go"
    volumes:
      - ./api:/go/src/api
    container_name: golang-container

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./api/db/init:/docker-entrypoint-initdb.d
      - ./api/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    container_name: mysql-container

volumes:
  db-data:
    driver: local
